spring:
  application:
    name: internet-banking
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:internetbanking
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    validation:
      enabled: true
server:
  port: 8081
  
internetbanking:
  openapi:
    dev-url: http://localhost:8081
    prod-url: http://localhost:8081